
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
